apiVersion: v1 # V1 da api do kubernetes
kind: ConfigMap # tipo cpnfig map, configura variaveis de ambiente
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
