kind: PersistentVolume #tipo do volume persistente, dados não são perdidos
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual # o nome é dado manualmente
  capacity:
    storage: 5Gi #capacidade do volume
  accessModes:
    - ReadWriteMany # modelo de acesso, varios podem ler e varios podem escrever
  hostPath:
    path: "/mnt/data" #caminho do banco de dados dentro do kubernetes
---
kind: PersistentVolumeClaim #atribuindo o volume criado ao app postgress 
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi